adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
	path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
	path('users/read/', adminapp.UsersListView.as_view(), name='users'),
	path('users/update/<int:pk>/', adminapp.UserEditView.as_view(), name='user_update'),
	path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),
	path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
	path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
	path('categories/update/<int:pk>/', adminapp.CategoryEditView.as_view(), name='category_update'),
	path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),
	path('news/create/', adminapp.NewsCreateView.as_view(), name='news_create'),
	path('news/<int:page>/', adminapp.NewsListView.as_view(), name='news_page'),
	path('news/read/<int:pk>/', adminapp.NewsDetailView.as_view(), name='news_read'),
	path('news/update/<int:pk>/', adminapp.NewsEditView.as_view(), name='news_update'),
	path('news/delete/<int:pk>/', adminapp.NewsDeleteView.as_view(), name='news_delete'),
	path('subscribers/', adminapp.SubscribersListView.as_view(), name='subscribers'),
	path('product/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
	path('product/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
	path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
	path('product/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
	path('product/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete')

]

authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('email_verify/', authapp.email_verify, name='email_verify')
]

historical_games/urls.py
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.conf import settings
from django.urls import include, path

from mainapp.views import SearchResultsView, NewsListView, NewsDetailView, ContactsFormView, ProductListView, \
    ProductDetailView, HomeView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
    path('', HomeView.as_view(), name='main'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('contacts/', ContactsFormView.as_view(), name='contacts'),
    path('thanks/', TemplateView.as_view(template_name='mainapp/thanks.html', extra_context={'title': 'success'}), name='thanks'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('about/', TemplateView.as_view(template_name='mainapp/about.html', extra_context={'title': 'About'}), name='about'),
    path('news/', NewsListView.as_view(), name='news'),
    path('news_<int:pk>/', NewsDetailView.as_view(), name="news_detail"),
    path('team/', TemplateView.as_view(template_name='mainapp/team.html', extra_context={'title': 'Team'}), name='team'),
    path('services/', TemplateView.as_view(template_name='mainapp/services.html', extra_context={'title': 'Services'}), name='services'),
    path('search/', SearchResultsView.as_view(), name="search_results")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from datetime import datetime
from unicodedata import decimal

from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="название", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="название игры", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    description = models.TextField(verbose_name="описание игры", blank=True)
    price = models.DecimalField(verbose_name="стоимость игры", max_digits=8, decimal_places=2,
                                default=0)
    quantity = models.IntegerField(verbose_name="количество на складе", default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @property
    def disc_price(self):
        return round(self.price / 2, 2)

    @property
    def get_price(self):
        if self.quantity >= 200:
            return self.disc_price
        else:
            return self.price

    @staticmethod
    def select_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class ProdPage(models.Model):
    id_prod = models.ForeignKey(Product, on_delete=models.CASCADE)
    img_1 = models.ImageField(upload_to="prod_page", blank=True)
    img_2 = models.ImageField(upload_to="prod_page", blank=True)
    img_3 = models.ImageField(upload_to="prod_page", blank=True)
    img_4 = models.ImageField(upload_to="prod_page", blank=True)

    def __str__(self):
        return self.id_prod.name


class News(models.Model):
    title = models.CharField(verbose_name="заголовок", max_length=64)
    published = models.DateField(verbose_name="опубликовано",
                                 default=datetime.now)
    updated = models.DateField(verbose_name='обновлено',
                               auto_now=True)
    short_desc = models.CharField(verbose_name="краткое описание",
                                  max_length=256)
    description = models.TextField(verbose_name="текст новости")
    img_1 = models.ImageField(upload_to="news", blank=True)
    img_2 = models.ImageField(upload_to="news", blank=True)
    img_3 = models.ImageField(upload_to="news", blank=True)
    is_active = models.BooleanField(verbose_name='активна',
                                    default=True)


class Subscribe(models.Model):
    client_email = models.EmailField(max_length=50, blank=False)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    checked = models.BooleanField()

    def __str__(self):
        return self.client_email

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, \
    ProductCategoryEditForm, ProductEditForm, NewsEditForm, ImgProductForm

from authapp.models import ShopUser
from mainapp.models import Product, ProductCategory, News, Subscribe
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db.models import F


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Админка / Пользователи'
        return context


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin:users')
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи / Создание'
        return context


class UserEditView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin:users')
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи / Редактирование'

        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Пользователи / Удаление'
        return context


class NewsCreateView(CreateView):
    model = News
    template_name = 'adminapp/news_update.html'
    success_url = reverse_lazy('admin:news_page', args=[1])
    form_class = NewsEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости / Создание'
        return context


class NewsListView(ListView):
    paginate_by = 3
    model = News
    template_name = 'adminapp/news_list.html'
    ordering = ['-published']

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Админка / Новости'
        return context


class NewsEditView(UpdateView):
    model = News
    template_name = 'adminapp/news_update.html'
    success_url = reverse_lazy('admin:news_page', args=[1])
    form_class = NewsEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости / Редактирование'
        return context


class NewsDetailView(DetailView):
    model = News
    template_name = 'adminapp/news_detail.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости / Отдельная новость'
        return context


class NewsDeleteView(DeleteView):
    model = News
    template_name = 'adminapp/news_delete.html'
    # success_url = reverse_lazy('admin:news_page', args=[1])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости / Удаление'
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('admin:news_page', args=[1]))


class CategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории / Создание'
        return context


class CategoriesListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Админка / Категории'
        return context


class CategoryEditView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории / Редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))

        return super().form_valid(form)


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)


class CategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории / Удаление'
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(reverse_lazy('admin:categories'))


class ProductCreateView(CreateView):
    form_class = ProductEditForm
    template_name = 'adminapp/product_update.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('admin:products', kwargs={'pk': self.object.category.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Продукты / Создание'
        context['category'] = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        if self.request.POST:
            context['img_form'] = ImgProductForm(self.request.POST, self.request.FILES)
        else:
            context['img_form'] = ImgProductForm()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        img_form = context['img_form']
        self.object = form.save(commit=False)
        self.object.category_id = self.kwargs['pk']
        self.object.save()
        if img_form.is_valid():
            prod_img = img_form.save(commit=False)
            prod_img.id_prod = self.object
            prod_img.save()
        return super().form_valid(form)


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products_list.html'
    paginate_by = 2

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <div class="row">
            <a class="btn btn-primary mt-3 mb-5 px-3 ml-5" role="button" href="{% url 'admin:category_create' %}">новая категория</a>
        </div>
        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href="{% url 'admin:products' object.pk %}">товары категории</a>
                    </button>
                    <button>
                        <a href="{% url 'admin:category_update' object.pk %}">редактировать</a>
                    </button>
                    {% if object.is_active %}
                        <button>
                            <a href="{% url 'admin:category_delete' object.pk %}">удалить</a>
                        </button>
                    {% else %}
                        <button>
                            <a href="{% url 'admin:category_delete' object.pk %}">восстановить</a>
                        </button>
                    {% endif %}
                </div>
                <div class="category_desc">
                    {{ object.description|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        {% if object.is_active %}
            Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?
        {% else %}
            Уверены, что хотите восстановить категорию <strong>{{ object.name }}</strong>?
        {% endif %}
        <form action="{% url 'admin:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            {% if object.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
             <input class="btn btn-primary" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:categories' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/news_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<h3>Заголовок: {{ object.title|title }}</h3>
	<h5 class="mt-3"> Дата публикации: {{ object.published }}</h5>
	<h5> Дата обновления: {{ object.updated }}</h5>
	<p class="mt-3"><b>Краткое описание:</b></p>
	<p class="mb-3">{{ object.short_desc }}</p>
	<p class="mt-3"><b>Текст статьи:</b></p>
	<p>{{ object.description }}</p>
	<h4 class="mt-4">Изображения новости</h4>
	<div class="row">
		<div class="col-4 col-sm-3 col-md-2">
			{% if object.img_1 %}
			<img class="img-fluid" src="/media/{{ object.img_1 }}" alt="img" style="max-height:180px;">
			{% endif %}
		</div>
		<div class="col-4 col-sm-3 col-md-2">
			{% if object.img_2 %}
			<img class="img-fluid" src="/media/{{ object.img_2 }}" alt="img" style="max-height:180px;">
			{% endif %}
		</div>
		<div class="col-4 col-sm-3 col-md-2">
			{% if object.img_3 %}
			<img class="img-fluid" src="/media/{{ object.img_3 }}" alt="img" style="max-height:180px;">
			{% endif %}
		</div>
	</div>
	<button class="btn btn-round form-control mt-4"><a class="small"
										href="{% url 'admin:news_update' object.pk %}">
						редактировать</a></button>
	<button class="btn btn-round form-control"><a class="small" href="{% url 'admin:news_delete' object.pk %}">
						удалить</a></button>
	<button class="btn btn-round form-control mb-5">
		<a href="{% url 'admin:news_page' 1 %}">
			к списку новостей
		</a>
	</button>
</div>

{% endblock %}

adminapp/templates/adminapp/news_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container">
	<div class="row">
		<a class="btn btn-primary mt-3 mb-5 px-3" role="button" href="{% url 'admin:news_create' %}">новая статья</a>
	</div>
		<div class="row justify-content-center">
		{% for object in page_obj %}
		<div class="col-8 col-sm-4 col-lg-3 mb-4 {% if not object.is_active %}not_active{% endif %}">
			<div class="card card-news" style="background: #f4f8fa;">
				<div class="card-body">
					<p><span class="date_p">{{object.published|date:"d"}}</span><span
							class="text_date">{{object.published|date:"F Y"}}</span></p>
					<h4>{{ object.title }}</h4>
					<p class="card-text">{{object.short_desc}}</p>
					<p class="mb-0"><a class="small" href="{% url 'admin:news_read' object.pk %}">
						подробнее...</a></p>
					<p class="mb-0"><a class="small" href="{% url 'admin:news_update' object.pk %}">
						редактировать</a></p>
					{% if object.is_active %}
					<p class="mb-0"><a class="small" href="{% url 'admin:news_delete' object.pk %}">
						удалить</a></p>
					{% else %}
					<p class="mb-0"><a class="small" href="{% url 'admin:news_delete' object.pk %}">
						восстановить</a></p>
					{% endif %}
				</div>
			</div>
		</div>
	    {% endfor %}
	</div>
</div>
<div class="pagination">
	{% if page_obj.has_previous %}
	<a href="{% url 'admin:news_page' page_obj.previous_page_number %}">&laquo</a>
	{% endif %}
	<span>{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
	{% if page_obj.has_next %}
	<a href="{% url 'admin:news_page' page_obj.next_page_number %}">
		&raquo</a>
	{% endif %}
</div>
{% endblock %}

adminapp/templates/adminapp/product.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
	<div class="prod_title_name mb-4"><h2>{{ object.name|title }} (Жанр: {{ object.category.name|title }})</h2></div>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-2">
				<img  class="img-fluid" src="/media/{{ object.image }}" alt="game">
			</div>
			<div class="col-2 product_actions">
				<button><a href="{% url 'admin:product_update' object.pk %}">редактировать</a></button>
				<button><a href="{% url 'admin:product_delete' object.pk %}">удалить</a>
				</button>
			</div>
			<div class="col-2 summary">
				<b>цена</b>
				<p>${{ object.price }}</p>
				<b>количество</b>
				<p>{{ object.quantity }}</p>
			</div>
			<div class="col-4 product_desc">
				{{ object.description|title }}
			</div>
		</div>
	</div>
	<div class="img_product_item mt-5">
		<p class="font-weight-bold">Изображения на странице product_page</p>
		<div class="media-small">
			{% if object.prodpage_set.first.img_1 %}
			<img src="/media/{{ object.prodpage_set.first.img_1 }}" alt="game">
			{% endif %}
			{% if object.prodpage_set.first.img_2 %}
			<img src="/media/{{ object.prodpage_set.first.img_2 }}" alt="game">
			{% endif %}
			{% if object.prodpage_set.first.img_3 %}
			<img src="/media/{{ object.prodpage_set.first.img_3 }}" alt="game">
			{% endif %}
			{% if object.prodpage_set.first.img_4 %}
			<img src="/media/{{ object.prodpage_set.first.img_4 }}" alt="game">
			{% endif %}
			{% if not object.prodpage_set.first %}
			<p class="mb-5">изображения отсутствуют</p>
			{% endif %}
		</div>
	</div>
	<button class="btn btn-round form-control mb-5">
            <a href="{% url 'admin:products' object.category.pk %}">
                к списку продуктов категории
            </a>
        </button>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        {% if object.is_active %}
            Уверены, что хотите удалить продукт <strong>{{ object.name }}</strong>?
        {% else %}
            Уверены, что хотите восстановить продукт <strong>{{ object.name }}</strong>?
        {% endif %}
        <form action="{% url 'admin:product_delete' object.pk %}" method="post">
            {% csrf_token %}
            {% if object.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
             <input class="btn btn-primary" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' object.category.pk %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
	<div class="row">
		<a class="btn btn-primary mt-3 mb-5 px-3" role="button" href="{% url 'admin:product_create' category.pk %}">новый продукт</a>
	</div>
	<div class="row justify-content-center">
	{% for object in object_list %}
		<div class="col-2 {% if not object.is_active %}not_active {% endif %}">
			<img  class="img-fluid" src="/media/{{ object.image }}" alt="{{ object.name }}">
		</div>
		<div class="col-2">Название: {{ object.name|title }}</div>
		<div class="col-2">
			<a class="btn btn-outline-primary px-3 mb-3" role="button" href="{% url 'admin:product_read' object.pk %}">подробнее</a>
			<a class="btn btn-outline-primary px-3 mb-3" role="button" href="{% url 'admin:product_update' object.pk %}">редактировать</a>
			<a class="btn btn-outline-primary px-3 mb-3" role="button" href="{% url 'admin:product_delete' object.pk %}">удалить</a>
		</div>
		<div class="col-2">
			<b>цена</b>
			<p>${{ object.price }}</p>
			<b>количество</b>
			{% if object.quantity >= 200 %}
			<p style="color:red">{{ object.quantity }}</p>
			{% else %}
			<p>{{ object.quantity }}</p>
			{% endif %}
		</div>
		<div class="col-4 mb-5">
			{{ object.description|title }}
		</div>
	{% endfor%}
	</div>

	<div class="pagination">
		{% if page_obj.has_previous %}
		<a href="?page={{ page_obj.previous_page_number }}">&laquo</a>
		{% endif %}
		<span>{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
		{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}">&raquo</a>
		{% endif %}
	</div>
</div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load myfilters %}

{% block content %}
    <div class="users_list">
		<div class="row">
			<a class="btn btn-primary px-3 mt-3 mb-5" role="button" href="{% url 'admin:user_create' %}">новый пользователь</a>
		</div>
		{% for object in object_list %}
			<div class="user_record {% if not object.is_active %}not_active{% endif %}">
				<img src="{{ object.avatar|user_img_filter }}" alt="{{ object.username }}">
				<div class="user_role">
					{% if object.is_superuser %}администратор{% else %}пользователь{% endif %}
					<button>
						<a href="{% url 'admin:user_update' object.pk %}">редактировать</a>
					</button>
					<button>
                        {% if object.is_active %}
						<a href="{% url 'admin:user_delete' object.pk %}">удалить</a>
                        {% else %}
                        <a href="{% url 'admin:user_delete' object.pk %}">восстановить</a>
                        {% endif %}
					</button>
				</div>
				<div class="user_name">
					<p><strong>{{ object.username }}</strong></p>
					<p>{% if object.first_name %}
						<b>{{ object.first_name|title }}</b>
						{% endif %}
					</p>
					<p>{% if object.last_name %}
					{{ object.last_name|title }}
					{% endif %}</p>

				</div>
				<div class="user_age">
					age:<br>
					{{ object.age }} лет
				</div>
				<div class="user_email">
					email:<br>
					{{ object.email }}
				</div>
				<div class="user_lastlogin">
					logged:<br>
					{{ object.last_login }}
				</div>
			</div>
		{% endfor%}
	</div>
{% endblock %}