authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('email_verify/', authapp.email_verify, name='email_verify')
]

basketapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
	path('', login_required(basketapp.BasketView.as_view()), name='view'),
	path('add/<int:pk>', basketapp.basket_add, name="add"),
	path('remove/<int:pk>', basketapp.basket_remove, name="remove"),
	path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name="edit"),
]

historical_games/urls.py
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.conf import settings
from django.urls import include, path

from mainapp.views import SearchResultsView, NewsListView, NewsDetailView, ContactsFormView, ProductListView, \
    ProductDetailView, HomeView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
    path('', HomeView.as_view(), name='main'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('contacts/', ContactsFormView.as_view(), name='contacts'),
    path('thanks/', TemplateView.as_view(template_name='mainapp/thanks.html', extra_context={'title': 'success'}), name='thanks'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('about/', TemplateView.as_view(template_name='mainapp/about.html', extra_context={'title': 'About'}), name='about'),
    path('news/', NewsListView.as_view(), name='news'),
    path('news_<int:pk>/', NewsDetailView.as_view(), name="news_detail"),
    path('team/', TemplateView.as_view(template_name='mainapp/team.html', extra_context={'title': 'Team'}), name='team'),
    path('services/', TemplateView.as_view(template_name='mainapp/services.html', extra_context={'title': 'Services'}), name='services'),
    path('search/', SearchResultsView.as_view(), name="search_results")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from datetime import datetime
from unicodedata import decimal

from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="название", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="название игры", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    description = models.TextField(verbose_name="описание игры", blank=True)
    price = models.DecimalField(verbose_name="стоимость игры", max_digits=8, decimal_places=2,
                                default=0)
    quantity = models.IntegerField(verbose_name="количество на складе", default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @property
    def disc_price(self):
        return round(self.price / 2, 2)

    @property
    def get_price(self):
        if self.quantity >= 200:
            return self.disc_price
        else:
            return self.price

    @staticmethod
    def select_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class ProdPage(models.Model):
    id_prod = models.ForeignKey(Product, on_delete=models.CASCADE)
    img_1 = models.ImageField(upload_to="prod_page", blank=True)
    img_2 = models.ImageField(upload_to="prod_page", blank=True)
    img_3 = models.ImageField(upload_to="prod_page", blank=True)
    img_4 = models.ImageField(upload_to="prod_page", blank=True)

    def __str__(self):
        return self.id_prod.name


class News(models.Model):
    title = models.CharField(verbose_name="заголовок", max_length=64)
    published = models.DateField(verbose_name="опубликовано",
                                 default=datetime.now)
    updated = models.DateField(verbose_name='обновлено',
                               auto_now=True)
    short_desc = models.CharField(verbose_name="краткое описание",
                                  max_length=256)
    description = models.TextField(verbose_name="текст новости")
    img_1 = models.ImageField(upload_to="news", blank=True)
    img_2 = models.ImageField(upload_to="news", blank=True)
    img_3 = models.ImageField(upload_to="news", blank=True)
    is_active = models.BooleanField(verbose_name='активна',
                                    default=True)


class Subscribe(models.Model):
    client_email = models.EmailField(max_length=50, blank=False)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    checked = models.BooleanField()

    def __str__(self):
        return self.client_email

mainapp/forms.py
from django import forms

from mainapp.models import Subscribe


class ContactForm(forms.Form):
    name = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'name', 'label':
        None}), max_length=50, required=True)
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'placeholder': 'email'}),
                             max_length=50, required=True)
    message = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'message'}),
                              required=True)


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['client_email']

mainapp/views.py
from itertools import chain

from django.conf.global_settings import DEFAULT_FROM_EMAIL
from django.core.mail import send_mail

from django.views.generic import ListView, DetailView, FormView, TemplateView
from django.views.generic.edit import FormMixin

from .models import Product, News, Subscribe
from django.db.models import Q
from mainapp.forms import ContactForm, SubscribeForm


class ContactsFormView(FormView):
    template_name = 'mainapp/contacts.html'
    form_class = ContactForm
    success_url = '/thanks/'
    extra_context = {'title': 'Contacts'}

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        recipients = ['usov.p@mail.ru']

        send_mail('сообщение с сайта historical_games',
                       f'от: {name}\nemail: {email}\n{message}', DEFAULT_FROM_EMAIL, recipients)

        return super().form_valid(form)


class HomeView(FormMixin, TemplateView):
    template_name = 'mainapp/index.html'
    form_class = ContactForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        context['products'] = Product.objects.filter(category__is_active=True).order_by('?')[:4]
        context['news_item'] = News.objects.filter(is_active=True).order_by('-published')[:3]
        context['subscribe_form'] = SubscribeForm()
        return context

    def post(self, request, *args, **kwargs):
        form = SubscribeForm(self.request.POST)
        if form.is_valid():
            return self.form_valid(form)
        view = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            client_email = form.cleaned_data['client_email']
            subscribe = Subscribe.objects.filter(client_email=client_email, checked=False).first()
            if not subscribe:
                Subscribe.objects.create(client_email=client_email, checked=False, is_active=True)
        return super().form_valid(form)


class ProductListView(FormMixin, ListView):
    model = Product
    queryset = Product.objects.filter(category__is_active=True, is_active=True).order_by('?')
    paginate_by = 8
    context_object_name = 'products'
    form_class = ContactForm
    success_url = '/thanks/'

    def post(self, request, *args, **kwargs):
        view = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disc_products'] = Product.objects.filter(Q(category__is_active=True) & Q(quantity__gte=200)).order_by('?')[:2]
        context['title'] = 'Catalog'
        return context


class ProductDetailView(FormMixin, DetailView):
    model = Product
    form_class = ContactForm
    success_url = '/thanks/'

    def post(self, request, *args, **kwargs):
        view = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['similar_products'] = Product.objects.filter(category__is_active=True, category=self.object.category).exclude(name=self.object.name).order_by('?')[:4].select_related('category')
        context['title'] = self.object.name
        context['discount_products'] = Product.objects.filter(category__is_active=True, quantity__gte=200).exclude(name=self.object.name).order_by('?')[:4]
        return context


class NewsListView(ListView):
    model = News
    queryset = News.objects.filter(is_active=True).order_by('-published')
    paginate_by = 3
    context_object_name = 'news'
    extra_context = {'title': 'News'}


class NewsDetailView(DetailView):
    model = News

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.pk
        return context


class SearchResultsView(ListView):
    template_name = 'mainapp/search_list.html'
    extra_context = {'title': 'Поиск'}

    def get_queryset(self):
        query = self.request.GET.get('q')
        query_sets = []
        query_sets.append(News.objects.filter(Q(title__icontains=query)|Q(
            short_desc__icontains=query)).filter(is_active=True).order_by('-published'))
        query_sets.append(Product.objects.filter(name__icontains=query).filter(is_active=True))
        object_list = list(chain(*query_sets))
        return object_list

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
{% load cache %}
<html>
<head>
	<meta charset="utf-8">
	{% block title %}
	<title>{{ title|title }}</title>
	{% endblock %}
	{% block links %}
	<link rel="stylesheet" type="text/css" href="{% static 'style/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style/style.css'%}">
	<link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300&display=swap" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	{% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block top_tab %}
<div class="top_tab">
	<div class="logo">
		<a href="{% url 'main' %}">
			<p class="logo_first">Historical</p>
			<p class="logo_second">GAMES</p>
		</a>
	</div>
	<div class="tel">
		<a href="#"><img src="{% static 'img/tel.png' %}" alt="tel"></a>
		<span class="text_tel">+123 456 7890</span>
		<a href="#"><img src="{% static 'img/email.png' %}" alt="email"></a>
		<span class="text_email">info@example.com</span>
	</div>
	<div class="search">
		<form action="{% url 'search_results' %}" method="get">
			<input name="q" type="text" placeholder="Search">
			<div><button><img src="{% static 'img/search.png' %}" alt="search"></button></div>
		</form>
	</div>
	{% if user.is_authenticated %}
	<a class= "login_icon" href="{% url 'auth:edit' %}" title= " {{ user.first_name|default:'Пользователь' }} "></a>
	{% else %}
	<a class= "login_icon" href="{% url 'auth:login' %}" title= "Вход/регистрация"></a>
	{% endif %}
	<a class= "basket" href="{% url 'basket:view' %}" title="
		{% if basket %}
			В козине {{ basket.0.total_quantity }} товаров на сумму ${{ basket.0.total_cost }}
		{% endif %}">
	</a>
	<span>
	{% if basket %}
		${{ basket.0.total_cost }} ({{ basket.0.total_quantity }} шт)
	{% endif %}
	</span>
</div>
{% endblock %}

{% block menu %}
{% endblock %}
</div>
{% block content %}
{% endblock %}
<div class="arrow">
	<img src="{% static 'img/arrow_top.png' %}" alt="arrow_top">
</div>

{% block contuct_us %}
<div class="contuct_us">
	<p class="cont_head">Contact Us</p>
	<div class="cont-box">
		<div class="box_left">
			<p class="box_left_head">Get in touch with us</p>
			<p class="box_left_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,sheets
			containing Lorem Ipsum passages sed do, At vero eos et accusamus et
			iusto odio digs qui blanditiis
			<br><br>
			Leningradsky AVE 39, BLDG 79
			MOSCOW 125167, Russia
			<br><br>
			Telephone : +00 111 222 3333
			<br><br>
			FAX : +1 888 888 4444
			<br><br>
			Email : <span id="mail">mail@example.com</span></p>
		</div>
		<div class="box_right">
			<form action="#" method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="form_sub">Submit</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}
{% block route %}
{% cache 3600 frame %}
<div class="route">
	<p class="route_head">Route Map</p>
	<div><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d8971.370422099419!2d37.5301096!3d55.7959709!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b549c0af2d5e3f%3A0xa77899d557548e3a!2sMail.Ru%20Group!5e0!3m2!1sru!2sru!4v1589671845786!5m2!1sru!2sru" width="1170" height="300" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe></div>
</div>
{% endcache %}
{% endblock %}
{% block footer %}
<div class="footer">
	<p>&copy;{% now "Y" %} Историческе Игры. Все права защищены</p>
</div>
{% endblock %}
{% block jquery %}
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'script.js'%}"></script>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}
	{% block header %}
    <div class="header-cont"></div>
	{% endblock %}
		{% block menu %}
		<div class="menu">
			{% include 'mainapp/include/inc_menu_gray.html' %}
			<hr class="gray">
			<div class="pull"></div>
		</div>
		{% endblock %}
	
	

mainapp/templates/mainapp/news_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
<title>News#{{ title }}</title>
{% endblock %}
{% block header %}
<div class="header-cont"></div>
{% endblock %}
    {% block menu %}
    <div class="menu">
        {% include 'mainapp/include/inc_menu_gray.html' %}
        <hr class="gray">
        <div class="pull"></div>
    </div>
    {% endblock %}
	{% block content %}
    <div class="container mt-5">
		<nav class="mx-5 mb-5" aria-label="breadcrumb">
		  	<ol class="breadcrumb">
		    	<li class="breadcrumb-item"><a href="{% url 'news' %}">News</a></li>
		    	<li class="breadcrumb-item active" aria-current="page">News#{{ title }}</li>
		  	</ol>
		</nav>
		<div class="row justify-content-center">
			<div class="col-6 col-sm-4 col-lg-3">
				<div id="carousel2" class="carousel slide">
                    <ol class="carousel-indicators">
                        <li data-target="#carousel2" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel2" data-slide-to="1"></li>
                        <li data-target="#carousel2" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner mb-4">
                        <div class="carousel-item active">
                            <img class="img-fluid d-block w-100" src="/media/{{object.img_1}}"
                                 alt="image">
                        </div>
                        <div class="carousel-item">
                            <img class="img-fluid d-block w-100" src="/media/{{object.img_2}}"
                                 alt="image">
                        </div>
                        <div class="carousel-item">
                            <img class="img-fluid d-block w-100" src="/media/{{object.img_3}}"
                                 alt="img">
                        </div>
                    </div>
  				</div>
			</div>
			<div class="col-8 col-sm-6 col-lg-5 mb-4">
				<h4 style="color:red;">{{object.title}}</h4>
				<p><span class="date_p">{{object.published|date:"d"}}</span><span
                        class="text_date">{{object.published|date:"F Y"}}</span></p>
				<p class="card-text">{{object.description}}</p>
			</div>
		</div>
	</div>
    {% endblock %}
    {% block contuct_us %}{% endblock %}
    {% block route %}{% endblock %}

mainapp/templates/mainapp/news_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block header %}
<div class="header-cont"></div>
{% endblock %}
    {% block menu %}
    <div class="menu">
        {% include 'mainapp/include/inc_menu_gray.html' %}
        <hr class="gray">
        <div class="pull"></div>
    </div>
    {% endblock %}
	{% block content %}
        <h3 class="cont_head text-center">Latest News</h3>
	<div class="container">
		<div class="row justify-content-center">
			{% include 'mainapp/include/inc_block_news.html' %}
		</div>
	</div>
	<div class="container">
		<div class="row justify-content-center">
			{% if page_obj.has_previous %}
			<div class="col-4 col-md-3 gallery-link">
				<a href="?page={{ page_obj.previous_page_number }}">Show prev news</a>
			</div>
			{% endif %}
			{% if page_obj.has_next %}
			<div class="col-4 col-md-3 gallery-link">
				<a href="?page={{ page_obj.next_page_number }}">Show more news</a>
			</div>
			{% endif %}
		</div>
	</div>
    {% endblock %}
    {% block contuct_us %}{% endblock %}
    {% block route %}{% endblock %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
	{% block header %}
	<div class="header-cont">
	{% endblock %}
		{% block menu %}
		<div class="menu">
			{% include 'mainapp/include/inc_menu_gray.html' %}
			<hr class="gray">
			<div class="pull"></div>
		</div>
		{% endblock %}
	{% block content %}
	<div class="product">
		<div class="product-box">
			<div class="product_left">
				<img class="big" src="/media/{{ object.prodpage_set.first.img_1 }}" alt="product">
				<div>
					<img class="select" src="/media/{{ object.prodpage_set.first.img_1 }}" alt="product_1">
					<img src="/media/{{ object.prodpage_set.first.img_2 }}" alt="product_2">
					<img src="/media/{{ object.prodpage_set.first.img_3 }}" alt="product_3">
					<img src="/media/{{ object.prodpage_set.first.img_4 }}" alt="product_4">
				</div>
				
			</div>
			<div class="product_right">
				<p class="product_text_1">{{ object.name }}</p>
				<p class="product_text_2">${{ object.get_price }}
				</p>
				<a href="{% url 'basket:add' object.pk %}"><button>Buy</button></a>
				<p class="product_text_3">{{ object.description }}</p>
			</div>
		</div>
	</div>
	{% if object.quantity < 200 %}
		<div class="similar">
		<p class="gallery-head similar-head">Similar-games</p>
		<div class="gallery-container">
			{% for item in similar_products %}
			<div class="gallery-box">
				<a href="{% url 'product_detail' item.pk %}"><img src="/media/{{item.image}}" width="271" height="376" alt="game"></a>
				<p class="movie">{{ item.name }}</p>
				<a href="{% url 'basket:add' item.pk %}"><button title ="купить за ${{ item.get_price }}">Buy</button></a>
			</div>
			{% endfor %}
		</div>	
	</div>
	{% else %}
		<div class="similar">
			<p class="gallery-head similar-head">HOT SALES</p>
			<div class="gallery-container">
				{% for item in discount_products %}
				<div class="gallery-box">
					<a href="{% url 'product_detail' item.pk %}"><img src="/media/{{item.image}}" width="271" height="376" alt="game"></a>
					<p class="movie">{{ item.name }}</p>
					<a href="{% url 'basket:add' item.pk %}"><button>Buy</button></a>
				</div>
				{% endfor %}
			</div>
		</div>
	{% endif %}
	</div>
	{% endblock %}

mainapp/templates/mainapp/product_discount_page.html
{% extends 'mainapp/base.html' %}
{% load static %}
	{% block header %}
	<div class="header-cont">
	{% endblock %}
		{% block menu %}
		<div class="menu">
			{% include 'mainapp/include/inc_menu_gray.html' %}
			<hr class="gray">
			<div class="pull"></div>
		</div>
		{% endblock %}
	{% block content %}
	<div class="product">
		<div class="product-box">
			<div class="product_left">
				<img class="big" src="/media/{{ disc_img.img_1 }}" alt="product">
				<div>
					<img class="select" src="/media/{{ disc_img.img_1 }}" alt="product_1">
					<img src="/media/{{ disc_img.img_2 }}" alt="product_2">
					<img src="/media/{{ disc_img.img_3 }}" alt="product_3">
					<img src="/media/{{ disc_img.img_4 }}" alt="product_4">
				</div>
				
			</div>
			<div class="product_right">
				<p class="product_text_1"><!-- Assasin’s Creed:<br><space>Rogue</space> -->
					{{ title_prod.name }}
				</p>
				<p class="product_text_2"><!-- $29.99 -->
					${{ title_prod.disc_price }}
				</p>
				<a href="{% url 'basket:add' disc_img.pk %}"><button>Buy</button></a>
				<!-- <p class="product_text_3">The plot is set in a fictional history of real world events an
				d follows the centuries-old struggle between the Assassins, who fight for peace with free will, and the Templars, who desire peace through control. The story is set in the mid-18th century during the Seven Years' War, and follows Shay Patrick Cormac, an Assassin-turned-Templar who hunts down former members of his Brotherhood after being betrayed by them. Gameplay in Rogue is very similar to that of Black Flag with a mixture of ship-based naval exploration and third-person land-based exploration with some new features.</p> -->
				<p class="product_text_3">{{ title_prod.description }}</p>
			</div>
		</div>
	</div>
	<div class="similar">
		<p class="gallery-head similar-head">HOT SALES</p>
		<div class="gallery-container">
			{% for item in discount_products %}
			<div class="gallery-box">
				<a href="{% url 'discount' item.pk %}"><img src="/media/{{item.image}}" width="271" height="376" alt="game"></a>
				<p class="movie">{{ item.name }}</p>
				<a href="{% url 'basket:add' item.pk %}"><button>Buy</button></a>
			</div>
			{% endfor %}
		</div>	
	</div>
	</div>
	{% endblock %}
	

mainapp/templates/mainapp/product_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
	{% block header %}
	<div class="header-cont">
	{% endblock %}
		{% block menu %}
		<div class="menu">
			{% include 'mainapp/include/inc_menu_gray.html' %}
			<hr class="gray">
			<div class="pull"></div>
		</div>
		{% endblock %}
	{% block content %}
	<div class="gallery">
		<p class="gallery-head">Our Gallery</p>
		<div class="gallery-container">
			{% include 'mainapp/include/inc_gallery-box.html' %}
		</div>
		<div class="d-flex justify-content-center">
			{% if page_obj.has_previous %}
			<div class="gallery-link mx-3">
				<a href="?page={{ page_obj.previous_page_number }}">Show prev games</a>
			</div>
			{% endif %}
			{% if page_obj.has_next %}
			<div class="gallery-link mx-3">
				<a href="?page={{ page_obj.next_page_number }}">Show more games ></a>
			</div>
			{% endif %}
		</div>
	</div>
	<div class="poster">
		{% for item in disc_products %}
		<div class="poster_left">
			<div class="poster-text">
				<p class="text_1">Discount</p>
				<a href="{% url 'product_detail' item.pk %}"><p class="text_2">{{ item.name }}</p></a>
				<p class="text_3">${{ item.disc_price }}<span>/</span><span id="price_1">${{ item.price }}</span></p>
				<a href="{% url 'basket:add' item.pk %}"><button>Buy</button></a>
			</div>
		</div>
		{% endfor %}
	</div>
	</div>
	{% endblock %}
	

mainapp/templates/mainapp/search_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block header %}
<div class="header-cont"></div>
{% endblock %}
    {% block menu %}
    <div class="menu">
        {% include 'mainapp/include/inc_menu_gray.html' %}
        <hr class="gray">
        <div class="pull"></div>
    </div>
    {% endblock %}
	{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center mt-5 mb-3">Результаты поиска</h1>
                {% if object_list %}
                    {% for object in object_list %}
                        <div>
                            {% if object.title %}
                            <a href="{% url 'news_detail' object.id %}">
                                <h2>{{ object.title }}</h2>
                            </a>
                            {{ object.short_desc|safe }}
                            <p><a class="btn btn-default btn-sm"
                                  href="{% url 'news_detail' object.id %}">
                                <strong>Читать далее</strong></a></p>
                            {% endif %}
                            {% if object.name %}
                            <a href="{% url 'product_page' object.id %}">
                                <h2>{{ object.name }}</h2>
                            </a>
                            {{ object.description|truncatewords_html:20 }}
                            <p><a class="btn btn-default btn-sm"
                                  href="{% url 'product_page' object.id %}"><strong>Читать
                                далее</strong></a></p>
                            {% endif %}

                        </div>
                    {% endfor %}

                {% else %}
                    <p>Не найдено публикаций по вашему запросу<br>Попробуйте повторить запрос с
                        другой формулировкой</p>
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}
    {% block contuct_us %}{% endblock %}
    {% block route %}{% endblock %}

mainapp/templates/mainapp/thanks.html
{% extends 'mainapp/base.html' %}
{% load static %}
	{% block header %}
	<div class="header-cont">
	{% endblock %}
		{% block menu %}
		<div class="menu">
			{% include 'mainapp/include/inc_menu_gray.html' %}
			<hr class="gray">
			<div class="pull"></div>
		</div>
		{% endblock %}
    {% block content%}
	<div class="container">
		<div class="row justify-content-center mt-5">
			<div class="col-11 col-md-6">
				<h4 style="line-height: 3.0rem;">Thank you for your inquiry. We will contact with
					you as soon as possible.</h4>
			</div>
		</div>
	</div>
    {% endblock %}
    {% block contuct_us %}{% endblock %}
    {% block route %}{% endblock %}