adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
	path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
	path('users/read/', adminapp.UsersListView.as_view(), name='users'),
	path('users/update/<int:pk>/', adminapp.UserEditView.as_view(), name='user_update'),
	path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),
	path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
	path('categories/read/', adminapp.CategoriesListView.as_view(), name='categories'),
	path('categories/update/<int:pk>/', adminapp.CategoryEditView.as_view(), name='category_update'),
	path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),
	path('news/create/', adminapp.NewsCreateView.as_view(), name='news_create'),
	path('news/<int:page>/', adminapp.NewsListView.as_view(), name='news_page'),
	path('news/read/<int:pk>/', adminapp.NewsDetailView.as_view(), name='news_read'),
	path('news/update/<int:pk>/', adminapp.NewsEditView.as_view(), name='news_update'),
	path('news/delete/<int:pk>/', adminapp.NewsDeleteView.as_view(), name='news_delete'),
	path('subscribers/', adminapp.SubscribersListView.as_view(), name='subscribers'),
	path('product/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
	path('product/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
	path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
	path('product/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
	path('product/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete')

]

authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('email_verify/', authapp.email_verify, name='email_verify')
]

basketapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
	path('', login_required(basketapp.BasketView.as_view()), name='view'),
	path('add/<int:pk>', basketapp.basket_add, name="add"),
	path('remove/<int:pk>', basketapp.basket_remove, name="remove"),
	path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name="edit"),
]

historical_games/urls.py
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.conf import settings
from django.urls import include, path

from mainapp.views import SearchResultsView, NewsListView, NewsDetailView, ContactsFormView, ProductListView, \
    ProductDetailView, HomeView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
    path('', HomeView.as_view(), name='main'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('contacts/', ContactsFormView.as_view(), name='contacts'),
    path('thanks/', TemplateView.as_view(template_name='mainapp/thanks.html', extra_context={'title': 'success'}), name='thanks'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('about/', TemplateView.as_view(template_name='mainapp/about.html', extra_context={'title': 'About'}), name='about'),
    path('news/', NewsListView.as_view(), name='news'),
    path('news_<int:pk>/', NewsDetailView.as_view(), name="news_detail"),
    path('team/', TemplateView.as_view(template_name='mainapp/team.html', extra_context={'title': 'Team'}), name='team'),
    path('services/', TemplateView.as_view(template_name='mainapp/services.html', extra_context={'title': 'Services'}), name='services'),
    path('search/', SearchResultsView.as_view(), name="search_results")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import re_path
import ordersapp.views as ordersapp

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    # path('', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

mainapp/models.py
from datetime import datetime
from unicodedata import decimal

from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="название", max_length=64, unique=True)
    description = models.TextField(verbose_name="описание", blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="название игры", max_length=128)
    image = models.ImageField(upload_to="products_images", blank=True)
    description = models.TextField(verbose_name="описание игры", blank=True)
    price = models.DecimalField(verbose_name="стоимость игры", max_digits=8, decimal_places=2,
                                default=0)
    quantity = models.IntegerField(verbose_name="количество на складе", default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

    @property
    def disc_price(self):
        return round(self.price / 2, 2)

    @property
    def get_price(self):
        if self.quantity >= 200:
            return self.disc_price
        else:
            return self.price

    @staticmethod
    def select_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class ProdPage(models.Model):
    id_prod = models.ForeignKey(Product, on_delete=models.CASCADE)
    img_1 = models.ImageField(upload_to="prod_page", blank=True)
    img_2 = models.ImageField(upload_to="prod_page", blank=True)
    img_3 = models.ImageField(upload_to="prod_page", blank=True)
    img_4 = models.ImageField(upload_to="prod_page", blank=True)

    def __str__(self):
        return self.id_prod.name


class News(models.Model):
    title = models.CharField(verbose_name="заголовок", max_length=64)
    published = models.DateField(verbose_name="опубликовано",
                                 default=datetime.now)
    updated = models.DateField(verbose_name='обновлено',
                               auto_now=True)
    short_desc = models.CharField(verbose_name="краткое описание",
                                  max_length=256)
    description = models.TextField(verbose_name="текст новости")
    img_1 = models.ImageField(upload_to="news", blank=True)
    img_2 = models.ImageField(upload_to="news", blank=True)
    img_3 = models.ImageField(upload_to="news", blank=True)
    is_active = models.BooleanField(verbose_name='активна',
                                    default=True)


class Subscribe(models.Model):
    client_email = models.EmailField(max_length=50, blank=False)
    is_active = models.BooleanField(verbose_name='активна', default=True)
    checked = models.BooleanField()

    def __str__(self):
        return self.client_email

mainapp/forms.py
from django import forms

from mainapp.models import Subscribe


class ContactForm(forms.Form):
    name = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'name', 'label':
        None}), max_length=50, required=True)
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'placeholder': 'email'}),
                             max_length=50, required=True)
    message = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'message'}),
                              required=True)


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['client_email']

mainapp/views.py
from itertools import chain

from django.conf.global_settings import DEFAULT_FROM_EMAIL
from django.core.mail import send_mail

from django.views.generic import ListView, DetailView, FormView, TemplateView
from django.views.generic.edit import FormMixin

from .models import Product, News, Subscribe
from django.db.models import Q
from mainapp.forms import ContactForm, SubscribeForm


class ContactsFormView(FormView):
    template_name = 'mainapp/contacts.html'
    form_class = ContactForm
    success_url = '/thanks/'
    extra_context = {'title': 'Contacts'}

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        recipients = ['usov.p@mail.ru']

        send_mail('сообщение с сайта historical_games',
                       f'от: {name}\nemail: {email}\n{message}', DEFAULT_FROM_EMAIL, recipients)

        return super().form_valid(form)


class HomeView(FormMixin, TemplateView):
    template_name = 'mainapp/index.html'
    form_class = ContactForm
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        context['products'] = Product.objects.filter(category__is_active=True).order_by('?')[:4]
        context['news_item'] = News.objects.filter(is_active=True).order_by('-published')[:3]
        context['subscribe_form'] = SubscribeForm()
        return context

    def post(self, request, *args, **kwargs):
        form = SubscribeForm(self.request.POST)
        if form.is_valid():
            return self.form_valid(form)
        view = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

    def form_valid(self, form):
        if form.is_valid():
            client_email = form.cleaned_data['client_email']
            subscribe = Subscribe.objects.filter(client_email=client_email, checked=False).first()
            if not subscribe:
                Subscribe.objects.create(client_email=client_email, checked=False, is_active=True)
        return super().form_valid(form)


class ProductListView(FormMixin, ListView):
    model = Product
    queryset = Product.objects.filter(category__is_active=True, is_active=True).order_by('?')
    paginate_by = 8
    context_object_name = 'products'
    form_class = ContactForm
    success_url = '/thanks/'

    def post(self, request, *args, **kwargs):
        view = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disc_products'] = Product.objects.filter(Q(category__is_active=True) & Q(quantity__gte=200)).order_by('?')[:2]
        context['title'] = 'Catalog'
        return context


class ProductDetailView(FormMixin, DetailView):
    model = Product
    form_class = ContactForm
    success_url = '/thanks/'

    def post(self, request, *args, **kwargs):
        view = ContactsFormView.as_view()
        return view(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['similar_products'] = Product.objects.filter(category__is_active=True, category=self.object.category).exclude(name=self.object.name).order_by('?')[:4].select_related('category')
        context['title'] = self.object.name
        context['discount_products'] = Product.objects.filter(category__is_active=True, quantity__gte=200).exclude(name=self.object.name).order_by('?')[:4]
        return context


class NewsListView(ListView):
    model = News
    queryset = News.objects.filter(is_active=True).order_by('-published')
    paginate_by = 3
    context_object_name = 'news'
    extra_context = {'title': 'News'}


class NewsDetailView(DetailView):
    model = News

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.pk
        return context


class SearchResultsView(ListView):
    template_name = 'mainapp/search_list.html'
    extra_context = {'title': 'Поиск'}

    def get_queryset(self):
        query = self.request.GET.get('q')
        query_sets = []
        query_sets.append(News.objects.filter(Q(title__icontains=query)|Q(
            short_desc__icontains=query)).filter(is_active=True).order_by('-published'))
        query_sets.append(Product.objects.filter(name__icontains=query).filter(is_active=True))
        object_list = list(chain(*query_sets))
        return object_list

mainapp/templates/mainapp/include/inc_block_news.html
{% for item in news %}
<div class="col-8 col-sm-4 col-lg-3 mb-4">
    <div class="card card-news" style="background: #f4f8fa;">
        <div class="card-body">
            <p>
                <span class="date_p">{{item.published|date:"d"}}</span>
                <span class="text_date">{{item.published|date:"F Y"}}</span>
            </p>
            <h4>{{item.title|title}}</h4>
            <p class="card-text">{{item.short_desc}}</p>
            <a class="small" href="{% url 'news_detail' item.pk%}">Read more...</a>
        </div>
    </div>
</div>
{% endfor %}

mainapp/templates/mainapp/include/inc_date_container.html
{% for item in news_item %}
<div class="date-container">
    <div class="date">
        <p class="date_p">{{ item.published|date:"d" }}</p>
        <p class="text_date">{{ item.published|date:"F" }}<br>{{ item.published|date:"Y" }}</p>
    </div>
    <div class="news_left_text">
        <a href="{% url 'news_detail'  item.pk %}"><p>{{ item.title }}</p></a>
        <p id="d-text_1">{{ item.short_desc }}</p>
    </div>
</div>
{% endfor %}

mainapp/templates/mainapp/include/inc_gallery-box.html
{% for item in products %}
<div class="gallery-box">
	<a href="{% url 'product_detail' item.pk %}"><img src="/media/{{ item.image }}" width="271" height="376" alt="game"></a>
	<div class="movie">{{ item.name }}</div>
	<a href="{% url 'basket:add' item.pk %}"><button title ="купить за ${{ item.price }}">Buy</button></a>
</div>
{% endfor %}

mainapp/templates/mainapp/include/inc_menu_gray.html
<ul class="gray">
	<li><a href="{% url 'main' %}">Home</a></li>
	<li><a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}gray-selected{% endif %}">About</a></li>
	<li><a href="{% url 'services' %}"
		   class="{% if request.resolver_match.url_name == 'services' %}gray-selected{% endif %}">Services</a></li>
	<li><a href="{% url 'catalog' %}" class="{% if request.resolver_match.url_name == 'catalog' %}gray-selected{% endif %}">Gallery</a></li>
	<li><a href="{% url 'news' %}" class="{% if request.resolver_match.url_name == 'news' %}gray-selected{% endif %}">News</a></li>
	<li><a href="{% url 'team' %}" class="{% if request.resolver_match.url_name == 'team' %}gray-selected{% endif %}">Team</a></li>
	<li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.url_name == 'contacts' %}gray-selected{% endif %}">Contact Us</a></li>
	<!-- {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
    {% endif %}-->
    <li>
        {% if user.is_authenticated %}
		<div class="dropdown">
			<a class="dropdown-toggle" href="" data-toggle="dropdown">
				{{ user.first_name|default:'Пользователь' }}
				<span class = "caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li>
					<a href="{% url 'auth:edit' %}">Профиль</a>
				</li>
				<li>
					<a href="{% url 'ordersapp:orders_list' %}">Мои заказы</a>
				</li>
				<li>
					<a href="{% url 'authapp:logout' %}">Выйти</a>
				</li>
			</ul>
		</div>
        {% endif %}
    </li>
	<li>{% if user.is_superuser %}<a href="{% url 'admin:users' %}">Админка</a>{% endif %}</li>
</ul>

mainapp/templates/mainapp/include/inc_menu_ul.html
<ul class="menu_ul">
	<li><a class="selected" href="{% url 'main' %}">Home</a></li>
	<li><a href="{% url 'about' %}">About</a></li>
	<li><a href="{% url 'services' %}">Services</a></li>
	<li><a href="{% url 'catalog' %}">Gallery</a></li>
	<li><a href="{% url 'news' %}">News</a></li>
	<li><a href="{% url 'team' %}">Team</a></li>
	<li><a href="{% url 'contacts' %}">Contact Us</a></li>
	<!-- {% if user.is_authenticated %}
        <li>
            <a href="{% url 'auth:edit' %}">
                {{ user.first_name|default:'Пользователь' }}
            </a>
        </li>
    {% endif %} -->
	<li>
        {% if user.is_authenticated %}
		<div class="dropdown">
			<a class="dropdown-toggle" href="" data-toggle="dropdown">
				{{ user.first_name|default:'Пользователь' }}
				<span class = "caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li>
					<a href="{% url 'auth:edit' %}">Профиль</a>
				</li>
				<li>
					<a href="{% url 'ordersapp:orders_list' %}">Мои заказы</a>
				</li>
				<li>
					<a href="{% url 'authapp:logout' %}">Выйти</a>
				</li>
			</ul>
		</div>
        {% endif %}
	</li>
	<li>{% if user.is_superuser %}<a href="{% url 'admin:users' %}">Админка</a>{% endif %}</li>
</ul>

mainapp/templates/mainapp/include/inc_social.html
{% load static %}
<div class="social">
	<a href="https://facebook.com"><div><img src="{% static 'img/facebook.png' %}" alt="facebook"></div></a>
	<a href="https://twitter.com"><div><img src="{% static 'img/twitter.png' %}" alt="twitter"></div></a>
	<a href="https://www.rss.ru"><div><img src="{% static 'img/rss.png' %}" alt="rss"></div></a>
	<a href="https://vk.com"><div><img src="{% static 'img/vk.png' %}" alt="vk"></div></a>
</div>