authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('email_verify/', authapp.email_verify, name='email_verify')
]

basketapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

import basketapp.views as basketapp

app_name = "basketapp"

urlpatterns = [
	path('', login_required(basketapp.BasketView.as_view()), name='view'),
	path('add/<int:pk>', basketapp.basket_add, name="add"),
	path('remove/<int:pk>', basketapp.basket_remove, name="remove"),
	path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name="edit"),
]

historical_games/urls.py
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.conf import settings
from django.urls import include, path

from mainapp.views import SearchResultsView, NewsListView, NewsDetailView, ContactsFormView, ProductListView, \
    ProductDetailView, HomeView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('', include('social_django.urls', namespace='social')),
    path('', HomeView.as_view(), name='main'),
    path('catalog/', ProductListView.as_view(), name='catalog'),
    path('contacts/', ContactsFormView.as_view(), name='contacts'),
    path('thanks/', TemplateView.as_view(template_name='mainapp/thanks.html', extra_context={'title': 'success'}), name='thanks'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('about/', TemplateView.as_view(template_name='mainapp/about.html', extra_context={'title': 'About'}), name='about'),
    path('news/', NewsListView.as_view(), name='news'),
    path('news_<int:pk>/', NewsDetailView.as_view(), name="news_detail"),
    path('team/', TemplateView.as_view(template_name='mainapp/team.html', extra_context={'title': 'Team'}), name='team'),
    path('services/', TemplateView.as_view(template_name='mainapp/services.html', extra_context={'title': 'Services'}), name='services'),
    path('search/', SearchResultsView.as_view(), name="search_results")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ordersapp/urls.py
from django.urls import re_path
import ordersapp.views as ordersapp

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    # path('', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

ordersapp/models.py
from django.conf import settings
from django.db import models

from basketapp.models import Basket
from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        # return sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return sum(list(map(lambda x: x.quantity * x.product.get_price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    @property
    def get_product_cost(self):
        # if (self.product.quantity >= 200):
        #     return self.product.disc_price * self.quantity
        # else:
        #     return self.product.price * self.quantity
        return self.product.get_price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required =False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['product'].queryset = Product.select_items()

ordersapp/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user) 


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    # if basket_items[num].product.quantity >= 200:
                    #     form.initial['price'] = basket_items[num].product.disc_price
                    # else:
                    #     form.initial['price'] = basket_items[num].product.price
                    form.initial['price'] = basket_items[num].product.get_price
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
           Basket.get_items(self.request.user).delete()
           form.instance.user = self.request.user
           self.object = form.save()
           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    # if form.instance.product.quantity >= 200:
                    #     form.initial['price'] = form.instance.product.disc_price
                    # else:
                    #     form.initial['price'] = form.instance.product.price
                    form.initial['price'] = form.instance.product.get_price
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
           self.object = form.save()
           if orderitems.is_valid():
               orderitems.instance = self.object
               orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsUpdate, self).form_valid(form)


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.get_price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>{{ title|title }}</title>
	{% block links %}
	<link rel="stylesheet" type="text/css" href="{% static 'style/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'style/style.css'%}">
	<link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300&display=swap" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	{% endblock %}
	{% block js %}
	{% endblock %}
</head>
<body>
	{% block header %}

	{% endblock %}
		{% block top_tab %}
		<div class="top_tab">
			<div class="logo">
				<a href="{% url 'main' %}">
					<p class="logo_first">Historical</p>
					<p class="logo_second">GAMES</p>
				</a>
			</div>
			<div class="tel">
				<a href="#"><img src="{% static 'img/tel.png' %}" alt="tel"></a>
				<span class="text_tel">+123 456 7890</span>
				<a href="#"><img src="{% static 'img/email.png' %}" alt="email"></a>
				<span class="text_email">info@example.com</span>
			</div>
			<div class="search">
				<input type="text" placeholder="Search">
				<div><a href="#"><img src="{% static 'img/search.png' %}" alt="search"></a></div>
			</div>
			{% if user.is_authenticated %}
			<a class= "login_icon" href="{% url 'auth:edit' %}" title= " {{ user.first_name|default:'Пользователь' }} "></a>
			{% else %}
			<a class= "login_icon" href="{% url 'auth:login' %}" title= "Вход/регистрация"></a>
			{% endif %}
			<a class= "basket" href="{% url 'basket:view' %}" title="
				{% if basket %}
					В козине {{ basket.0.total_quantity }} товаров на сумму ${{ basket.0.total_cost }}
				{% endif %}">
			</a>
			<span>
				{% if basket %}
					${{ basket.0.total_cost }} ({{ basket.0.total_quantity }} шт)
				{% endif %}
			</span>
		</div>
		{% endblock %}

		{% block menu %}

		{% endblock %}

    {% block content %}

	{% endblock %}
	<div class="arrow">
		<img src="{% static 'img/arrow_top.png' %}" alt="arrow_top">
	</div>

	{% block footer %}
	<div class="footer">
		<p>&copy;{% now "Y" %} Историческе Игры. Все права защищены</p>
	</div>
	{% endblock %}
	{% block jquery %}
	<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'jquery.formset.js' %}"></script>
	<script src="{% static 'orders_script.js' %}"></script>
	{% endblock %}
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-5">
        <h2>Уверены, что хотите удалить?</h2>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
            <button class="btn btn-success">
            <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
        </button>
        </form>

    </div>

{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    {% for item in object.orderitems.select_related %}
    <div class="basket_record">
        <img src="/media/{{ item.product.image }}" width="120" height="160" alt="product">
        <p class="category_name">{{ item.product.category.name }}</p>
        <p class="product_name">{{ item.product.name }}</p>
        <p class="product_price">
            <!--{% if item.product.quantity >= 200 %}${{ item.product.disc_price }}{% else %}
            ${{ item.product.price }}{% endif %}-->
            ${{ item.product.get_price }}
            </p>
        <p class="product_quantity"> x {{ item.quantity }} шт.</p>
        <p class="product_cost">${{ item.get_product_cost }}</p>
    </div>
    {% endfor %}
    {% include 'ordersapp/includes/inc_order_actions.html' %}
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="container">
    <form class="order_form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ orderitems.management_form }}
        {% for form in orderitems.forms %}
            {% if forloop.first %}
        <div class="row">
            {% for field in form.visible_fields %}
            <div class="col">{{ field.label|capfirst }}</div>
            {% endfor %}
        </div>
        <hr>
            {% endif %}
        <div class="row formset_row">
            {% for field in form.visible_fields %}
            <div class="col">
                {% if forloop.first %}
                    {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {% if field.name != 'price' %}
                    {{ field }}
                {% else %}
                    {% if field.value %}
                        <span>$</span><span class="orderitems-{{forloop.parentloop.counter0}}-price">{{ field.value }}</span>
                    {% endif %}
                {% endif %}
<!--                {{ field }}-->
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <button type = "submit" value = "сохранить" class = "btn btn-default btn-round form-control last">сохранить</button>
        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </form>
</div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block header %}
    <div class="header-cont"></div>
{% endblock %}
		{% block menu %}
		<div class="menu">
			{% include 'mainapp/include/inc_menu_gray.html' %}
			<hr class="gray">
			<div class="pull"></div>
		</div>
		{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Ваши заказы, {% if user.first_name %} {{ user.first_name|title}}
        {% else %} Пользователь {% endif %}
    </h2>
    <div class="row justify-content-center mt-4">
        <div class="col-md-1">ID</div>
        <div class="col-md-2">Создан</div>
        <div class="col-md-2">Обновлен</div>
        <div class="col-md-2">Статус</div>
        <div class="col-md-5 text-center">Действия</div>
    </div>
    <hr>
    <div class="row justify-content-center">
        {% for item in object_list %}
        {% if item.is_active %}
        <div class="col-md-1">{{ item.pk }}</div>
        <div class="col-md-2">{{ item.created|date:"Y-m-d H:i:s" }}</div>
        <div class="col-md-2">{{ item.updated|date:"Y-m-d H:i:s" }}</div>
        <div class="col-md-2">{{ item.get_status_display }}</div>
        <div class="col-md-2"><a href="{% url 'ordersapp:order_read' item.pk %}">посмотреть</a></div>
        <div class="col-md-2">{% if item.status == 'FM' %}
            <a href="{% url 'ordersapp:order_update' item.pk %}">редактировать</a>{% endif %}
        </div>
        <div class="col-md-1">{% if item.status == 'FM' %}
            <a href="{% url 'ordersapp:order_delete' item.pk %}">удалить</a>{% endif %}
        </div>
        {% endif %}
        {% endfor %}
    </div>
    <div class="row mt-5">
        <div class="col">
            <button class = "btn btn-default btn-round">
                <a href = "{% url 'main' %}">на главную</a>
            </button>
            <button class = "btn btn-default btn-round">
                <a href= "{% url 'ordersapp:order_create' %}">новый</a>
            </button>
        </div>
    </div>

</div>

{% endblock %}